language: csharp
dist: trusty
sudo: false

mono: none
dotnet: 3.0.0

install:
  - dotnet restore

script:
  - dotnet build -c Release
  - dotnet test -c Release src/WakeOnLan.Tests/WakeOnLan.Tests.csproj

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: src/WakeOnLan/bin/Release/*.nupkg
    skip_cleanup: true
    on:
      branch: master
      tags: true
  - provider: script
    skip-cleanup: true
    script: dotnet nuget push -k $NUGET_KEY -s https://api.nuget.org/v3/index.json src/WakeOnLan/bin/Release/*.nupkg
    on:
      branch: master
      tags: true
