configuration: Release

before_build:
  - choco install dotnetcore-sdk
  - dotnet restore
build_script:
  - dotnet build
test_script:
  - dotnet test src\WakeOnLan.Tests
after_build:
  - dotnet pack src\WakeOnLan -o artifacts
artifacts:
  - path: src\WakeOnLan\artifacts\*.nupkg
